import React, { createContext, useContext, useState } from 'react';

const translations = {
  en: {
    home: 'Home',
    rooms: 'Rooms',
    events: 'Events',
    bookYourRoom: 'Book Your Room',
    checkInDate: 'Check-in Date',
    checkOutDate: 'Check-out Date',
    guests: 'Guests',
    addToCart: '→ Book Now',
    planYourEvent: 'Plan Your Special Event',
    proceedToPayment: 'Proceed to Payment',
    checkout: 'Checkout',
    orders: 'Orders',
    profile: 'Profile',
    cart: 'Cart',
    logout: 'Logout',
    login: 'Login',
    bookingConfirmed: 'Booking Confirmed!',
    viewMenu: 'View Menu',
    eventType: 'Event Type',
    eventPackage: 'Package',
    expectedGuests: 'Expected Guests',
    guestReviews: 'Guest Reviews',
    writeReview: '+ Write a Review',
    yourName: 'Your Name',
    rating: 'Rating',
    yourReview: 'Your Review',
    submitReview: 'Submit Review',
    excellent: 'Excellent',
    good: 'Good',
    average: 'Average',
    poor: 'Poor',
    terrible: 'Terrible',
    reviews: 'reviews',
    shareExperience: 'Share your experience...',
    amenities: 'Amenities',
    pricePerNight: '/ night',
    total: 'Total',
    paymentMethod: 'Payment Method',
    payBeforeDelivery: 'Pay before delivery',
    payAfterDelivery: 'Pay after delivery',
    placeOrder: 'Place your order',
    specialEvent: 'Special Event',
    standardPackage: 'Standard Package',
    premiumPackage: 'Premium Package',
    luxuryPackage: 'Luxury Package',
    darkMode: 'Dark Mode',
    language: 'Language'
  },
  es: {
    home: 'Inicio',
    rooms: 'Habitaciones',
    events: 'Eventos',
    bookYourRoom: 'Reserve Su Habitación',
    checkInDate: 'Fecha de Entrada',
    checkOutDate: 'Fecha de Salida',
    guests: 'Huéspedes',
    addToCart: '→ Reservar Ahora',
    planYourEvent: 'Planifique Su Evento Especial',
    proceedToPayment: 'Proceder al Pago',
    checkout: 'Compra',
    orders: 'Pedidos',
    profile: 'Perfil',
    cart: 'Carrito',
    logout: 'Cerrar Sesión',
    login: 'Iniciar Sesión',
    bookingConfirmed: '¡Reserva Confirmada!',
    viewMenu: 'Ver Menú',
    eventType: 'Tipo de Evento',
    eventPackage: 'Paquete',
    expectedGuests: 'Huéspedes Esperados',
    guestReviews: 'Reseñas de Huéspedes',
    writeReview: '+ Escribir una Reseña',
    yourName: 'Su Nombre',
    rating: 'Calificación',
    yourReview: 'Su Reseña',
    submitReview: 'Enviar Reseña',
    excellent: 'Excelente',
    good: 'Bueno',
    average: 'Promedio',
    poor: 'Pobre',
    terrible: 'Terrible',
    reviews: 'reseñas',
    shareExperience: 'Comparta su experiencia...',
    amenities: 'Servicios',
    pricePerNight: '/ noche',
    total: 'Total',
    paymentMethod: 'Método de Pago',
    payBeforeDelivery: 'Pagar antes de la entrega',
    payAfterDelivery: 'Pagar después de la entrega',
    placeOrder: 'Realizar pedido',
    specialEvent: 'Evento Especial',
    standardPackage: 'Paquete Estándar',
    premiumPackage: 'Paquete Premium',
    luxuryPackage: 'Paquete De Lujo',
    darkMode: 'Modo Oscuro',
    language: 'Idioma'
  },
  fr: {
    home: 'Accueil',
    rooms: 'Chambres',
    events: 'Événements',
    bookYourRoom: 'Réservez Votre Chambre',
    checkInDate: 'Date d\'Arrivée',
    checkOutDate: 'Date de Départ',
    guests: 'Invités',
    addToCart: '→ Réserver Maintenant',
    planYourEvent: 'Planifiez Votre Événement Spécial',
    proceedToPayment: 'Procéder au Paiement',
    checkout: 'Paiement',
    orders: 'Commandes',
    profile: 'Profil',
    cart: 'Panier',
    logout: 'Déconnexion',
    login: 'Connexion',
    bookingConfirmed: 'Réservation Confirmée!',
    viewMenu: 'Voir le Menu',
    eventType: 'Type d\'Événement',
    eventPackage: 'Forfait',
    expectedGuests: 'Invités Attendus',
    guestReviews: 'Avis des Clients',
    writeReview: '+ Écrire un Avis',
    yourName: 'Votre Nom',
    rating: 'Évaluation',
    yourReview: 'Votre Avis',
    submitReview: 'Soumettre un Avis',
    excellent: 'Excellent',
    good: 'Bon',
    average: 'Moyen',
    poor: 'Mauvais',
    terrible: 'Terrible',
    reviews: 'avis',
    shareExperience: 'Partagez votre expérience...',
    amenities: 'Équipements',
    pricePerNight: '/ nuit',
    total: 'Total',
    paymentMethod: 'Mode de Paiement',
    payBeforeDelivery: 'Payer avant la livraison',
    payAfterDelivery: 'Payer après la livraison',
    placeOrder: 'Passer la commande',
    specialEvent: 'Événement Spécial',
    standardPackage: 'Forfait Standard',
    premiumPackage: 'Forfait Premium',
    luxuryPackage: 'Forfait Luxe',
    darkMode: 'Mode Sombre',
    language: 'Langue'
  },
  sw: {
    home: 'Nyumbani',
    rooms: 'Vyumba',
    events: 'Matukio',
    bookYourRoom: 'Mbolea Chumba Chako',
    checkInDate: 'Tarehe ya Kuingia',
    checkOutDate: 'Tarehe ya Kuondoka',
    guests: 'Wageni',
    addToCart: '→ Bukia Sasa',
    planYourEvent: 'Panga Tukio Lako la Ziada',
    proceedToPayment: 'Endelea na Malipo',
    checkout: 'Malipo',
    orders: 'Maagizo',
    profile: 'Wasifu',
    cart: 'Kikapu',
    logout: 'Toka',
    login: 'Ingia',
    bookingConfirmed: 'Bokering Imethibitishwa!',
    viewMenu: 'Tazama Menyu',
    eventType: 'Aina ya Tukio',
    eventPackage: 'Kifurushi',
    expectedGuests: 'Wageni Wanaosubiriwa',
    guestReviews: 'Maoni ya Wageni',
    writeReview: '+ Andika Maoni',
    yourName: 'Jina Lako',
    rating: 'Ukadiriaji',
    yourReview: 'Maoni Yako',
    submitReview: 'Tuma Maoni',
    excellent: 'Kitamu Sana',
    good: 'Nzuri',
    average: 'Wastani',
    poor: 'Duni',
    terrible: 'Mbaya Sana',
    reviews: 'maoni',
    shareExperience: 'Sambaza uzoefu wako...',
    amenities: 'Huduma',
    pricePerNight: '/ usiku',
    total: 'Jumla',
    paymentMethod: 'Mbinu ya Malipo',
    payBeforeDelivery: 'Lipa kabla ya utoaji',
    payAfterDelivery: 'Lipa baada ya utoaji',
    placeOrder: 'Weka Agizo',
    specialEvent: 'Tukio Maalum',
    standardPackage: 'Kifurushi cha Kawaida',
    premiumPackage: 'Kifurushi cha Premium',
    luxuryPackage: 'Kifurushi cha Pindi',
    darkMode: 'Hali Giza',
    language: 'Lugha'
  }
};

const LanguageContext = createContext();

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem('language') || 'en';
  });

  const t = (key) => {
    return translations[language]?.[key] || translations.en[key] || key;
  };

  const changeLanguage = (lang) => {
    setLanguage(lang);
    localStorage.setItem('language', lang);
  };

  return (
    <LanguageContext.Provider value={{ language, t, changeLanguage, availableLanguages: Object.keys(translations) }}>
      {children}
    </LanguageContext.Provider>
  );
};
